# Generated by Django 3.1.7 on 2021-03-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20210325_0226'),
        ('customer', '0003_auto_20210325_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_table',
            fields=[
                ('cart_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('total_iteams', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customertable')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstable')),
            ],
        ),
    ]
