# Generated by Django 3.1.7 on 2021-03-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_Table',
            new_name='ProductsTable',
        ),
    ]
