# Generated by Django 3.1.7 on 2021-04-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210325_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstable',
            name='image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
