# Generated by Django 3.1.7 on 2021-04-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productstable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstable',
            name='product_intro',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
