# Generated by Django 3.1.7 on 2021-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productstable_product_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstable',
            name='product_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
