# Generated by Django 3.1.7 on 2021-04-09 17:54

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productstable_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstable',
            name='product_link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
