# Generated by Django 3.1.7 on 2021-03-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210324_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Table',
            new_name='CustomerTable',
        ),
    ]
