# Generated by Django 3.1.7 on 2021-03-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customertable_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertable',
            name='customer_location',
        ),
        migrations.AlterField(
            model_name='customertable',
            name='customer_email',
            field=models.TextField(),
        ),
    ]
