# Generated by Django 3.1.7 on 2021-03-25 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20210325_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productstable')),
            ],
        ),
    ]
